# Generated by Django 6.0.2 on 2026-03-12 11:34

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('locataire', 'Locataire'), ('proprietaire', 'Propriétaire'), ('agence', 'Agence'), ('non_defini', 'Non défini'), ('admin', 'Administrateur')], default='non_defini', max_length=20)),
                ('verification_status', models.CharField(choices=[('aucun', 'Aucun'), ('en_attente', 'En attente'), ('verifie', 'Vérifié'), ('rejete', 'Rejeté')], default='aucun', max_length=20)),
                ('is_onboarding_complete', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo_profil', models.ImageField(blank=True, upload_to='profils/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalMaison',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix_location', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('publiee', 'Publiée'), ('rejetee', 'Rejetée'), ('suspendue', 'Suspendue')], default='brouillon', max_length=20)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('raison_rejet', models.TextField(blank=True)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proprietaire', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role__in': ['proprietaire', 'agence']}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical maison',
                'verbose_name_plural': 'historical maisons',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUserVerificationDocument',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('document_type', models.CharField(choices=[('identite', "Pièce d'identité"), ('titre_propriete', 'Titre de propriété'), ('kbis_agence', 'KBIS / Registre agence')], max_length=20)),
                ('file', models.TextField(max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=15)),
                ('uploaded_at', models.DateTimeField(blank=True, editable=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role__in': ['admin']}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user verification document',
                'verbose_name_plural': 'historical user verification documents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix_location', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('publiee', 'Publiée'), ('rejetee', 'Rejetée'), ('suspendue', 'Suspendue')], default='brouillon', max_length=20)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('raison_rejet', models.TextField(blank=True)),
                ('proprietaire', models.ForeignKey(limit_choices_to={'role__in': ['proprietaire', 'agence']}, on_delete=django.db.models.deletion.PROTECT, related_name='maisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDocumentMaison',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('type_document', models.CharField(choices=[('titre_propriete', 'Titre de propriété de cette maison'), ('acte_vente', 'Acte de vente de cette maison'), ('mandat_gestion', 'Mandat de gestion (si agence)'), ('autorisation_location', 'Autorisation de location'), ('diagnostic_performance', 'Diagnostic de performance énergétique'), ('certificat_conformite', 'Certificat de conformité'), ('assurance_habitation', 'Assurance habitation'), ('taxe_habitation', "Taxe d'habitation"), ('autre', 'Autre document')], max_length=50)),
                ('fichier', models.TextField(max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('numero_document', models.CharField(blank=True, max_length=100)),
                ('date_emission', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('expire', 'Expiré')], default='en_attente', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(blank=True, editable=False)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verifie_par', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role__in': ['admin']}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('maison', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nde.maison')),
            ],
            options={
                'verbose_name': 'historical document maison',
                'verbose_name_plural': 'historical document maisons',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DocumentMaison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('type_document', models.CharField(choices=[('titre_propriete', 'Titre de propriété de cette maison'), ('acte_vente', 'Acte de vente de cette maison'), ('mandat_gestion', 'Mandat de gestion (si agence)'), ('autorisation_location', 'Autorisation de location'), ('diagnostic_performance', 'Diagnostic de performance énergétique'), ('certificat_conformite', 'Certificat de conformité'), ('assurance_habitation', 'Assurance habitation'), ('taxe_habitation', "Taxe d'habitation"), ('autre', 'Autre document')], max_length=50)),
                ('fichier', models.FileField(upload_to='documents_maisons/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('numero_document', models.CharField(blank=True, max_length=100)),
                ('date_emission', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('expire', 'Expiré')], default='en_attente', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('verifie_par', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_maisons_verifies', to=settings.AUTH_USER_MODEL)),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='nde.maison')),
            ],
            options={
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='UserVerificationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('document_type', models.CharField(choices=[('identite', "Pièce d'identité"), ('titre_propriete', 'Titre de propriété'), ('kbis_agence', 'KBIS / Registre agence')], max_length=20)),
                ('file', models.FileField(upload_to='verification/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=15)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reviewer', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
