# Generated by Django 6.0.2 on 2026-05-06

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nde", "0003_historicalmaison_latitude_historicalmaison_longitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerNotification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("type", models.CharField(choices=[("maison_suspendue", "Maison suspendue")], default="maison_suspendue", max_length=40)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("reason", models.TextField(blank=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("maison", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notifications", to="nde.maison")),
                ("user", models.ForeignKey(limit_choices_to={"role__in": ["proprietaire", "agence"]}, on_delete=django.db.models.deletion.CASCADE, related_name="owner_notifications", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalOwnerNotification",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("type", models.CharField(choices=[("maison_suspendue", "Maison suspendue")], default="maison_suspendue", max_length=40)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("reason", models.TextField(blank=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
                ("history_user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("maison", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="nde.maison")),
                ("user", models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={"role__in": ["proprietaire", "agence"]}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "historical owner notification",
                "verbose_name_plural": "historical owner notifications",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
