# Generated by Django 6.0.2 on 2026-07-05 05:44

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nde", "0006_pvit_to_kpay"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalListingSubscriptionPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("amount_xaf", models.PositiveIntegerField()),
                ("merchant_reference", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("paid", "Payé"),
                            ("failed", "Échec"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("kpay_transaction_id", models.CharField(blank=True, max_length=191)),
                ("webhook_payload", models.JSONField(blank=True, null=True)),
                ("init_response", models.JSONField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical listing subscription payment",
                "verbose_name_plural": "historical listing subscription payments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ListingSubscriptionPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("amount_xaf", models.PositiveIntegerField()),
                (
                    "merchant_reference",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("paid", "Payé"),
                            ("failed", "Échec"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("kpay_transaction_id", models.CharField(blank=True, max_length=191)),
                ("webhook_payload", models.JSONField(blank=True, null=True)),
                ("init_response", models.JSONField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="contactreveal",
            options={},
        ),
        migrations.RenameIndex(
            model_name="contactreveal",
            new_name="nde_contact_user_id_4ed39d_idx",
            old_name="nde_contact_user_id_bd7e8c_idx",
        ),
        migrations.AddField(
            model_name="remoteuser",
            name="listing_subscription_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Fin de validité de l'abonnement annonces illimitées (paiement via KPay).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="remoteuser",
            name="listing_trial_used",
            field=models.BooleanField(
                default=False,
                help_text="Empêche de relancer l'essai gratuit de 14 jours (agences vérifiées, usage unique).",
            ),
        ),
        migrations.AlterField(
            model_name="contactaccesspayment",
            name="merchant_reference",
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name="historicallistingsubscriptionpayment",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicallistingsubscriptionpayment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listingsubscriptionpayment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing_subscription_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
