# Generated by Django 6.0.2 on 2026-07-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nde", "0007_listing_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoteuser",
            name="deactivation_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Motif affiché à l'utilisateur lorsque son compte est désactivé (is_active=False).",
            ),
        ),
    ]
