# Generated by Django 6.0.2 on 2026-07-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nde", "0008_remoteuser_deactivation_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoteuser",
            name="terms_accepted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date d'acceptation des CGU (obligatoire pour utiliser l'application).",
                null=True,
            ),
        ),
    ]
