# Generated by Django 6.0.2 on 2026-07-05 22:09

import cloudinary_storage.storage
import django.core.validators
import nde.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nde", "0009_remoteuser_terms_accepted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentmaison",
            name="fichier",
            field=models.FileField(
                storage=nde.storages.PrivateRawMediaCloudinaryStorage(),
                upload_to="documents_maisons/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalphotomaison",
            name="image",
            field=models.TextField(
                max_length=100,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="photomaison",
            name="image",
            field=models.ImageField(
                upload_to="photos_maisons/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="piecejointecommentaire",
            name="fichier",
            field=models.FileField(
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="commentaires/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userverificationdocument",
            name="file",
            field=models.FileField(
                storage=nde.storages.PrivateRawMediaCloudinaryStorage(),
                upload_to="verification/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
