# Generated by Django 6.0.2 on 2026-07-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nde', '0010_alter_documentmaison_fichier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmaison',
            name='publication_latitude',
            field=models.FloatField(blank=True, help_text="Position GPS de l'appareil au moment de la création de l'annonce (traçabilité anti-fraude).", null=True),
        ),
        migrations.AddField(
            model_name='historicalmaison',
            name='publication_longitude',
            field=models.FloatField(blank=True, help_text="Position GPS de l'appareil au moment de la création de l'annonce (traçabilité anti-fraude).", null=True),
        ),
        migrations.AddField(
            model_name='maison',
            name='publication_latitude',
            field=models.FloatField(blank=True, help_text="Position GPS de l'appareil au moment de la création de l'annonce (traçabilité anti-fraude).", null=True),
        ),
        migrations.AddField(
            model_name='maison',
            name='publication_longitude',
            field=models.FloatField(blank=True, help_text="Position GPS de l'appareil au moment de la création de l'annonce (traçabilité anti-fraude).", null=True),
        ),
    ]
