"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import firebase_admin
from firebase_admin import credentials
from decouple import config

BASE_DIR = Path(__file__).resolve().parent.parent

#firebase configuration

FIREBASE_KEY_PATH = BASE_DIR/"secrets/ndeapp-e97ab-firebase-adminsdk-fbsvc-8bb2facda4.json"
cred = credentials.Certificate(FIREBASE_KEY_PATH)
firebase_admin.initialize_app(cred)



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default="django-insecure-3jw6+rdg258bkfp8@$tpt@k2i6&ilrwq6c7l_=0(r)q!zbc1-z")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "cloudinary_storage",
    "django.contrib.staticfiles",
    "cloudinary",
    "django.contrib.sites",
    "simple_history",
    "rest_framework.authtoken",
    "django.contrib.postgres",
    "drf_yasg",
    "django_filters",
    "django_extensions",
    'rest_framework',
    'rest_framework_simplejwt',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google', # Pour Google
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'nde',

]
SITE_ID = 1

# Configuration Allauth
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_ADAPTER = 'nde.adapters.CustomSocialAccountAdapter'
OLD_PASSWORD_FIELD_ENABLED = True
LOGIN_ON_EMAIL_CONFIRMATION = True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            # On utilise l'ID Web pour le backend
            'client_id': config('GOOGLE_WEB_CLIENT_ID', default=''), 
            'secret': config('SOCIALACCOUNT_GOOGLE_SECRET', default=''),
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

MIDDLEWARE = [
   "corsheaders.middleware.CorsMiddleware",  # CORS pour le front-end
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"
AUTH_USER_MODEL = "nde.RemoteUser"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.debug",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Determine if we're running inside Docker or locally
# If running locally, use localhost and the mapped port
# If running in Docker, use the service name and internal port
import socket
def is_running_in_docker():
    try:
        # Check if we're in a Docker container by looking for Docker-specific files
        with open('/proc/1/cgroup', 'r') as f:
            return 'docker' in f.read()
    except FileNotFoundError:
        # If the file doesn't exist, we're likely not in Docker
        return False

if is_running_in_docker():
    db_host = config('POSTGRES_HOST', default='nde-db')
    db_port = config('POSTGRES_PORT', default='5432')
else:
    # When running locally, always use localhost and the mapped port
    db_host = 'localhost'
    db_port = config('DB_PORT', default='8012')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('POSTGRES_DB'),
        'USER': config('POSTGRES_USER'),
        'PASSWORD': config('POSTGRES_PASSWORD'),
        'HOST': config('POSTGRES_HOST'),  # Doit lire "nde-db"
        'PORT': config('POSTGRES_PORT', default='5432'), # Doit lire "5432"
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Cloudinary : stockage des fichiers uploadés (photos, documents). Retombe sur le disque local
# tant qu'aucun identifiant n'est configuré (dev par défaut), pour ne rien casser sans compte
# Cloudinary. Les clés doivent toutes être présentes (même vides) pour que l'import du package
# ne lève pas d'erreur au démarrage.
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME', default=''),
    'API_KEY': config('CLOUDINARY_API_KEY', default=''),
    'API_SECRET': config('CLOUDINARY_API_SECRET', default=''),
}
CLOUDINARY_ENABLED = bool(
    CLOUDINARY_STORAGE['CLOUD_NAME']
    and CLOUDINARY_STORAGE['API_KEY']
    and CLOUDINARY_STORAGE['API_SECRET']
)

STORAGES = {
    "default": {
        "BACKEND": (
            "cloudinary_storage.storage.MediaCloudinaryStorage"
            if CLOUDINARY_ENABLED
            else "django.core.files.storage.FileSystemStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# Google OAuth callback URL (doit correspondre au redirect_uri du frontend)
GOOGLE_OAUTH_CALLBACK_URL = config('GOOGLE_OAUTH_CALLBACK_URL')
REST_AUTH = {
    'USER_DETAILS_SERIALIZER': 'nde.serializers.users.usersSerializer.RemoteUserSerializer',
}

# JWT Configuration pour dj-rest-auth
REST_USE_JWT = True
JWT_AUTH_COOKIE = 'nde-auth'
JWT_AUTH_REFRESH_COOKIE = 'nde-refresh-token'
JWT_AUTH_HTTPONLY = False  # Set to True in production with HTTPS

# CORS Configuration (à adapter selon votre domaine front-end)
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://192.168.1.65:8080",
    "http://192-168-1-65.sslip.io:8080",
]

# Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='NDE Location <noreply@nde.com>')

# Durée de validité des liens de réinitialisation de mot de passe (24h).
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24

# URLs publiques (callback serveur KPay, retour passerelle éventuel).
BACKEND_PUBLIC_URL = config("BACKEND_PUBLIC_URL", default="http://127.0.0.1:8002")
FRONTEND_PUBLIC_URL = config("FRONTEND_PUBLIC_URL", default="http://localhost:8080")

# Locataires : contacts gratuits puis pass payant via KPay (Mobile Money, XAF).
CONTACT_ACCESS_FREE_VIEWS = config("CONTACT_ACCESS_FREE_VIEWS", default=5, cast=int)
CONTACT_ACCESS_PRICE_XAF = config("CONTACT_ACCESS_PRICE_XAF", default=500, cast=int)
CONTACT_ACCESS_SUBSCRIPTION_DAYS = config(
    "CONTACT_ACCESS_SUBSCRIPTION_DAYS", default=30, cast=int
)

# Propriétaires/agences : quota d'annonces gratuit puis abonnement payant via KPay (Mobile Money, XAF).
LISTING_PROPRIETAIRE_FREE_DAILY_QUOTA = config(
    "LISTING_PROPRIETAIRE_FREE_DAILY_QUOTA", default=2, cast=int
)
LISTING_PROPRIETAIRE_SUBSCRIPTION_PRICE_XAF = config(
    "LISTING_PROPRIETAIRE_SUBSCRIPTION_PRICE_XAF", default=5000, cast=int
)
LISTING_AGENCE_SUBSCRIPTION_PRICE_XAF = config(
    "LISTING_AGENCE_SUBSCRIPTION_PRICE_XAF", default=20000, cast=int
)
LISTING_SUBSCRIPTION_DAYS = config("LISTING_SUBSCRIPTION_DAYS", default=30, cast=int)
LISTING_TRIAL_DAYS = config("LISTING_TRIAL_DAYS", default=14, cast=int)

# KPay Sandbox / prod — docs officielles (X-API-Key + X-Secret-Key, POST /api/v1/payments/init).
KPAY_API_BASE_URL = config("KPAY_API_BASE_URL", default="https://admin.kpay.site")
KPAY_HTTP_TIMEOUT_SECONDS = config("KPAY_HTTP_TIMEOUT_SECONDS", default=30, cast=int)

# Clés API (tableau de bord KPay) : kpay_test_… / sk_test_… en sandbox, kpay_live_… / sk_live_… en prod.
KPAY_API_KEY = config("KPAY_API_KEY", default="")
KPAY_SECRET_KEY = config("KPAY_SECRET_KEY", default="")

# Description affichée au client sur la page de paiement hébergée.
KPAY_PAYMENT_DESCRIPTION = config(
    "KPAY_PAYMENT_DESCRIPTION", default="Pass contacts annonces NDE"
)

# Secret webhook KPay : HMAC-SHA256 (hex) calculé sur le corps brut, en-tête X-KPAY-Signature.
KPAY_WEBHOOK_SECRET = config("KPAY_WEBHOOK_SECRET", default="")
KPAY_WEBHOOK_SIGNATURE_HEADER = config(
    "KPAY_WEBHOOK_SIGNATURE_HEADER", default="X-KPAY-Signature"
)

# Secret de signature du retour passerelle (returnUrl : status|reference|externalId|ts).
# Non documenté séparément par KPay à ce jour — à ajuster si le tableau de bord en fournit un
# distinct ; par défaut, on retombe sur KPAY_SECRET_KEY (X-Secret-Key).
KPAY_GATEWAY_SECRET = config("KPAY_GATEWAY_SECRET", default="")

# Celery : broker/backend Redis (service "nde-redis" en local/Docker).
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default=CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE